name: brokr
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  flutter_dotenv: ^5.0.2
  intl: ^0.18.0
  get: ^4.6.5
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.7
  path_provider: ^2.0.11
  provider: ^6.0.5
  animated: ^2.0.0
  card_loading: ^0.2.2
  cached_network_image: ^3.2.3
  pinput: ^2.2.21
  country_picker: ^2.0.19
  google_fonts: ^3.0.1
  modal_bottom_sheet: ^2.1.2
  custom_navigation_bar: ^0.8.2
  google_maps_flutter: ^2.2.3
  custom_map_markers: ^0.0.2+1
  dropdown_button2: ^1.9.2
  grouped_list: ^5.1.2
  table_calendar: ^3.0.9
  flutter_settings_screens: ^0.3.3-null-safety+2
  equatable: ^2.0.5
  lottie: ^2.2.0
  mask_text_input_formatter: ^2.4.0
  font_awesome_flutter: ^10.3.0
  iconsax: ^0.0.8
  share_plus: ^6.3.1
  fl_chart: ^0.61.0
  toggle_switch: ^2.0.1
  flutter_expanded_tile: ^0.3.7
  geolocator: ^9.0.2
  animate_do: ^3.0.2
  image_picker: ^0.8.6+4
  dotted_border: ^2.0.0+3
  flutter_keyboard_visibility: ^5.4.0
  barcode_scan2: ^4.2.3
  camera: ^0.10.3+2
  flutter_mobile_vision_2: ^0.1.15
  permission_handler: ^10.2.0
  google_mlkit_text_recognition: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
   # - enviroment/dotenv.debug
   # - enviroment/dotenv.prod